// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3RXtsTJts9Ha2yN_o-8v50wJf0yAqFtE',
    appId: '1:355864788702:web:d2fe49423d2350442d4c4f',
    messagingSenderId: '355864788702',
    projectId: 'supervisor-app-iu',
    authDomain: 'supervisor-app-iu.firebaseapp.com',
    storageBucket: 'supervisor-app-iu.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1X9ZRwa9kugHxMyq4egMIHQiNlZl8Fno',
    appId: '1:355864788702:android:eb0c89cd22de780e2d4c4f',
    messagingSenderId: '355864788702',
    projectId: 'supervisor-app-iu',
    storageBucket: 'supervisor-app-iu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPRwaa5cIdRqYkjvq8kMFa3sCFZOmTq9Y',
    appId: '1:355864788702:ios:a9bd1629c2e5e5a12d4c4f',
    messagingSenderId: '355864788702',
    projectId: 'supervisor-app-iu',
    storageBucket: 'supervisor-app-iu.appspot.com',
    iosBundleId: 'com.example.supervisorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPRwaa5cIdRqYkjvq8kMFa3sCFZOmTq9Y',
    appId: '1:355864788702:ios:a9bd1629c2e5e5a12d4c4f',
    messagingSenderId: '355864788702',
    projectId: 'supervisor-app-iu',
    storageBucket: 'supervisor-app-iu.appspot.com',
    iosBundleId: 'com.example.supervisorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3RXtsTJts9Ha2yN_o-8v50wJf0yAqFtE',
    appId: '1:355864788702:web:8b396865214359df2d4c4f',
    messagingSenderId: '355864788702',
    projectId: 'supervisor-app-iu',
    authDomain: 'supervisor-app-iu.firebaseapp.com',
    storageBucket: 'supervisor-app-iu.appspot.com',
  );
}
